# docker exec -i -t altezza-travel-mariadb /bin/bash
# docker exec -i -t altezza-travel-php-fpm /bin/bash
# docker exec -i -t altezza-travel-webserver /bin/bash

version: "3.3"
services:

    mariadb:
      image: mariadb:10.2
      container_name: altezza-travel-mariadb
      working_dir: /altezza-travel
      volumes:
        - .:/altezza-travel
      environment:
        - MYSQL_ROOT_PASSWORD=altezza-travel
        - MYSQL_USER=altezza-travel
        - MYSQL_PASSWORD=altezza-travel
        - MYSQL_DATABASE=altezza-travel
      privileged: true
      networks:
        subnet:
          ipv4_address: 172.21.1.2

    webserver:
      image: nginx:1.14.1-alpine
      container_name: altezza-travel-webserver
      working_dir: /altezza-travel
      privileged: true
      volumes:
          - .:/altezza-travel
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
        subnet:
          ipv4_address: 172.21.1.3

    php-fpm:
      build: docker/php-fpm
      container_name: altezza-travel-php-fpm
      working_dir: /altezza-travel
      privileged: true
      volumes:
        - .:/altezza-travel
      networks:
        subnet:
          ipv4_address: 172.21.1.4

networks:
  subnet:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16